### Data Cleaning Script

```{r}
#| message: false
library(tidyverse)
library(here)
```

```{r}
files <- list.files(path = here("data"), pattern = "*.csv", full.names = TRUE)
raw_data <- map_df(files, ~read_csv(.x, 
                                    show_col_types = FALSE,
                                    col_select = -Rk) %>%
                     mutate(year = str_extract(.x, "\\d{4}")))
```

```{r}
clean_data <- raw_data %>% 
  filter(Pos == 'QB') %>%
  filter(GS > 3) %>%
  filter(Att > 50) %>%
  group_by(Player, year) %>% 
  slice_max(order_by = GS, n = 1, with_ties = FALSE) %>% 
  ungroup() %>%
  separate(QBrec, into = c("Wins"), sep = "-", extra = "drop", convert = TRUE) %>%
  select(
    c("year", "Player", "Age", "GS", "Wins", "Cmp", "Att", "Cmp%","Yds...11", "TD", "Int", "Succ%", "Rate", "QBR", "Sk")
  ) %>% 
  rename(Yards = Yds...11, Completions = Cmp, Attempts = Att, Comp_Percentage = `Cmp%`, Interceptions = Int, Sacks = Sk)
```

```{r}
write_csv(clean_data, here("data", "cleaned_data.csv"))
```